[package]
name = "arma-stats"
version = "0.1.0"
authors = ["Albert Hafvenström <albhaf@gmail.com>"]

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
libc = "0.2.6"
lazy_static = "0.1.15"
serde_json = "0.7.0"
hyper = "0.8.0"
time = "0.1"

[dev-dependencies]
iron = "0.3.0"
router = "0.1.1"
